language: java
jdk:
  - openjdk8

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - docker build -t thanhndse/demo-docker:latest .
  - docker push
  - ./mvnw heroku:deploy -P deploy-heroku

after_success:
  - bash <(curl -s https://codecov.io/bash)