language: java
jdk:
  - openjdk8

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
script:
  - ./mvnw clean install
  - docker build -t thanhndse/demo-docker:latest -t thanhndse/demo-docker:1.0 .
  - docker push thanhndse/demo-docker:1.0
  - docker push thanhndse/demo-docker:latest
  - ./mvnw heroku:deploy -P deploy-heroku-staging
after_success:
  - bash <(curl -s https://thanhnd-demo-docker.herokuapp.com/)