language: java
jdk:
  - openjdk8
script:
  - ./mvnw clean install
  - ./mvnw heroku:deploy -P deploy-heroku-staging
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
  - docker build -t thanhndse/demo-docker:latest -t thanhndse/demo-docker:1.0 .
  - docker push thanhndse/demo-docker:1.0
  - docker push thanhndse/demo-docker:latest